name: CI for Web Project

on: [push, pull_request]

jobs:
  javascript-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; else echo "No package.json"; fi

      - name: Run JavaScript tests
        run: |
          if [ -f package.json ]; then npm test || echo "JS tests failed or not defined"; else echo "No JS tests defined"; fi

  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install dependencies
        run: |
          if [ -f composer.json ]; then composer install; else echo "No composer.json found"; fi

      - name: Run PHP tests
        run: |
          if [ -f ./vendor/bin/phpunit ]; then ./vendor/bin/phpunit || echo "PHP tests failed"; else echo "No PHP tests found"; fi
