ذا احسن منه ؟ name: Run PHP & JS Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # إعداد PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Install PHP dependencies
        run: composer install

      - name: Run PHP tests
        run: |
          ./vendor/bin/phpunit --log-junit phpunit-report.xml

      # إعداد Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install JS dependencies
        run: npm install

      - name: Run JS tests
        run: |
          npm test -- --ci --reporters=default --reporters=jest-junit
        env:
          JEST_JUNIT_OUTPUT: jest-report.xml

      # رفع تقارير الاختبار
      - name: Upload PHP report
        uses: actions/upload-artifact@v3
        with:
          name: phpunit-report
          path: phpunit-report.xml

      - name: Upload JS report
        uses: actions/upload-artifact@v3
        with:
          name: jest-report
          path: jest-report.xml
